### PR TITLE
Update To new Bugfix. Add some Features

### PR DESCRIPTION
**Pull request by ils15**
I already update firmware to latest bugfix

Your version is a lot of behind of that

I already created a branch to mantain developing and plaining to versioning firmware

Features | Implemented
-- | --
Advanced Pause | YES
Mesh Bed Leveling | YES
Corneling Leveling | YES
Display Percentage | NO
Junction Deviation | YES (0.08)
TMC UART | YES
BLTOUCH | YES (BL version)
Filament Sensor | NO
Neopixel | Ready
EEPROM | YES (STM32 Flash)

Please refer to  this [repo](https://github.com/ils15/MKS-Robin-E3D/)

### CODE REVIEW

**Comment by makerbase-mks** [comment]
Hi! I has build your firmware, but have some error, can you solve it?
image

**Comment by monkiki** [comment]
Great! I was able to compile it. I will test later.

**Comment by ils15** [comment]
> Hi! I has build your firmware, but have some error, can you solve it?
> image

compiled fine here. Reupload my folder. Please Check it

**Comment by ils15** [comment]
> Great! I was able to compile it. I will test later.

Good. Please post results

**Comment by makerbase-mks** [comment]
MKS has update to marlin2.0.6 version

**Pull request closed without merging**
