### PR TITLE
Make M500 available / Save Settings to Flash with EEPROM Emulation

### PR DESCRIPTION
**Pull request by DocYester**
So we can save settings by using the regualr M500 command from Marlin.
Settings are saved to flash by using eeprom emulation

### CODE REVIEW

**Comment by makerbase-mks** [comment]
Thanks for your feedback, it looks great.

**Comment by gromgit** [comment]
> You can setup 512kb as maximum flash size. Same thing was introduced in skr board for the same STM32F103RCT6 chip. I tried and it works.

@jfranch, I'm surprised it worked for you, since the STM32F103RCT6 has only 256KB flash, according to [STMicro's own datasheet](https://www.st.com/resource/en/datasheet/stm32f103rc.pdf). The equivalent 512KB part# is STM32F103R**E**T6.

**Comment by jfranch** [comment]
> > You can setup 512kb as maximum flash size. Same thing was introduced in skr board for the same STM32F103RCT6 chip. I tried and it works.
> 
> @jfranch, I'm surprised it worked for you, since the STM32F103RCT6 has only 256KB flash, according to [STMicro's own datasheet](https://www.st.com/resource/en/datasheet/stm32f103rc.pdf). The equivalent 512KB part# is STM32F103R**E**T6.

Look at this URI's:
https://www.reddit.com/r/ender3/comments/dsmf6x/512k_flash_working_on_skr_mini_e3_v12/
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/87
Changes are available in Marlin for SKR Mini E3 with STM32F103RCT6

**Comment by DocYester** [comment]
But use that as MEMORY MAP 👍 
```
MEMORY
{
  ram (rwx) : ORIGIN = 0x20000000, LENGTH = 48K - 40
  rom (rx)  : ORIGIN = 0x08005000, LENGTH = 512K - 20K - 4K
}
```

rom beginning at 0x08007000 will let the update stuck at 100% and no more boot is possible

**Comment by jfranch** [comment]
I don't remember exactly what I modified. Later I can send you exact files I tried and works. I can flash an marilin that not fit on 256kb and additionally 4kb of EEPROM.

**Comment by DocYester** [comment]
Added all that is needed to get 512kb flash end save settings with M500

**Comment by jfranch** [comment]
image
mks_robin_e3.ld

**Comment by jfranch** [comment]
image
pins_mks_robin_e3d.h

**Comment by jfranch** [comment]
for an "official" release maybe we can create another platformio environment like [env:mks_robin_e3_512]. By this way everyone can choose 256 or 512kb.

**Comment by DocYester** [comment]
I think i would rather make a new PR to Marlin directly ... 11 days here looks fine and nothing else ?!
Still on 2.0.5.0 here with lots of bugs so you cant compile it without 2hrs of searching around ...

**Comment by jfranch** [comment]
Totally agree, no support from makerbase. If you put pullrequest to marlin notify me and I vote

**Comment by gromgit** [comment]
> for an "official" release maybe we can create another platformio environment like [env:mks_robin_e3_512]. By this way everyone can choose 256 or 512kb.

Yes, that's the way to go, because 512KB on RCT6 is _not_ guaranteed to work. Given what I've seen of semiconductor manufacturing processes, I suspect all Rx chips are physically identical (i.e. 512KB flash), then are badged as RC, RD, or RE after testing failures or market demands. In the latter case, 512KB may work perfectly fine, but the former is a crap shoot.

**Comment by DocYester** [comment]
When we talk about chaces - well ... using the first like 20kb of the "unofficial" 256k is like 10% chance of failure (just to get some numbers) , then lets say its about 10% of them were failed in testing (anf not just relabeled due overproduction) and another 10% that has the failures in the first 20kb ... we're down at 0,1% chance to have a fault flash that we really use ... that's ok for me to get some more features enabled in marlin

**Comment by DocYester** [comment]
went over to the official bugfix branch for the first part ...
https://github.com/MarlinFirmware/Marlin/pull/18219
next PR with 512k for e3 / e3d will be there in some days

**Pull request closed without merging**
